from whosplot.run import Run
from whosplot.utility import create_empty_data_csv


class MyStyle(Run):
    def __init__(self):
        super(MyStyle, self).__init__()

    def my_figure(self):
        items = [
            {
                "shape": "superellipsoid",
                "a1": 1.0,
                "a2": 1.0,
                "a3": 1.0,
                "e1": 4,
                "e2": 4,
                "nu": 100,
                "nv": 100,
                "view": (15, 15),
            },
            {
                "shape": "superellipsoid",
                "a1": 1.0,
                "a2": 1.0,
                "a3": 1.0,
                "e1": 4,
                "e2": 1,
                "nu": 100,
                "nv": 100,
                "view": (15, 15),
            },
            {
                "shape": "superellipsoid",
                "a1": 1.0,
                "a2": 1.0,
                "a3": 1.0,
                "e1": 2,
                "e2": 2,
                "nu": 100,
                "nv": 100,
                "view": (15, 15),
            },
            {
                "shape": "superellipsoid",
                "a1": 1.0,
                "a2": 1.0,
                "a3": 1.0,
                "e1": 1,
                "e2": 1,
                "nu": 100,
                "nv": 100,
                "view": (15, 15),
            },
            {
                "shape": "superellipsoid",
                "a1": 1.0,
                "a2": 1.0,
                "a3": 1.0,
                "e1": 0.2,
                "e2": 1,
                "nu": 100,
                "nv": 100,
                "view": (15, 15),
            },
            {
                "shape": "superellipsoid",
                "a1": 1.0,
                "a2": 1.0,
                "a3": 1.0,
                "e1": 0.2,
                "e2": 0.2,
                "nu": 100,
                "nv": 100,
                "view": (15, 15),
            },
            {
                "shape": "superellipsoid",
                "a1": 1.2,
                "a2": 1.0,
                "a3": 0.8,
                "e1": 4,
                "e2": 4,
                "nu": 100,
                "nv": 100,
                "view": (15, 15),
            },
            {
                "shape": "superellipsoid",
                "a1": 1.2,
                "a2": 1.0,
                "a3": 0.8,
                "e1": 4,
                "e2": 1,
                "nu": 100,
                "nv": 100,
                "view": (15, 15),
            },
            {
                "shape": "superellipsoid",
                "a1": 1.2,
                "a2": 1.0,
                "a3": 0.8,
                "e1": 2,
                "e2": 2,
                "nu": 100,
                "nv": 100,
                "view": (15, 15),
            },
            {
                "shape": "superellipsoid",
                "a1": 1.2,
                "a2": 1.0,
                "a3": 0.8,
                "e1": 1,
                "e2": 1,
                "nu": 100,
                "nv": 100,
                "view": (15, 15),
            },
            {
                "shape": "superellipsoid",
                "a1": 1.2,
                "a2": 1.0,
                "a3": 0.8,
                "e1": 0.2,
                "e2": 1,
                "nu": 100,
                "nv": 100,
                "view": (15, 15),
            },
            {
                "shape": "superellipsoid",
                "a1": 1.2,
                "a2": 1.0,
                "a3": 0.8,
                "e1": 0.2,
                "e2": 0.2,
                "nu": 100,
                "nv": 100,
                "view": (15, 15),
            },
            {
                "shape": "superellipsoid",
                "a1": 1,
                "a2": 0.2,
                "a3": 0.2,
                "e1": 4,
                "e2": 4,
                "nu": 100,
                "nv": 100,
                "view": (15, 15),
            },
            {
                "shape": "superellipsoid",
                "a1": 1,
                "a2": 0.2,
                "a3": 0.2,
                "e1": 4,
                "e2": 1,
                "nu": 100,
                "nv": 100,
                "view": (15, 15),
            },
            {
                "shape": "superellipsoid",
                "a1": 1,
                "a2": 0.2,
                "a3": 0.2,
                "e1": 2,
                "e2": 2,
                "nu": 100,
                "nv": 100,
                "view": (15, 15),
            },
            {
                "shape": "superellipsoid",
                "a1": 1,
                "a2": 0.2,
                "a3": 0.2,
                "e1": 1,
                "e2": 1,
                "nu": 100,
                "nv": 100,
                "view": (15, 15),
            },
            {
                "shape": "superellipsoid",
                "a1": 1,
                "a2": 0.2,
                "a3": 0.2,
                "e1": 0.2,
                "e2": 1,
                "nu": 100,
                "nv": 100,
                "view": (15, 15),
            },
            {
                "shape": "superellipsoid",
                "a1": 1,
                "a2": 0.2,
                "a3": 0.2,
                "e1": 0.2,
                "e2": 0.2,
                "nu": 100,
                "nv": 100,
                "view": (15, 15),
            },
        ]

        text = [
            "$\\varepsilon_1=\\varepsilon_2=4$\n$a_1=a_2=a_3=1$",
            "$\\varepsilon_1=4, \\varepsilon_2=1$\n$a_1=a_2=a_3=1$",
            "$\\varepsilon_1=\\varepsilon_2=2$\n$a_1=a_2=a_3=1$",
            "$\\varepsilon_1=\\varepsilon_2=1$\n$a_1=a_2=a_3=1$",
            "$\\varepsilon_1=0.2, \\varepsilon_2=1$\n$a_1=a_2=a_3=1$",
            "$\\varepsilon_1=\\varepsilon_2=0.2$\n$a_1=a_2=a_3=1$",
            "$\\varepsilon_1=\\varepsilon_2=4$\n$a_1=1.2, a_2=1, a_3=0.8$",
            "$\\varepsilon_1=4, \\varepsilon_2=1$\n$a_1=1.2, a_2=1, a_3=0.8$",
            "$\\varepsilon_1=\\varepsilon_2=2$\n$a_1=1.2, a_2=1, a_3=0.8$",
            "$\\varepsilon_1=\\varepsilon_2=1$\n$a_1=1.2, a_2=1, a_3=0.8$",
            "$\\varepsilon_1=0.2, \\varepsilon_2=1$\n$a_1=1.2, a_2=1, a_3=0.8$",
            "$\\varepsilon_1=\\varepsilon_2=0.2$\n$a_1=1.2, a_2=1, a_3=0.8$",
            "$\\varepsilon_1=\\varepsilon_2=4$\n$a_1=1, a_2=0.2, a_3=0.2$",
            "$\\varepsilon_1=4, \\varepsilon_2=1$\n$a_1=1, a_2=0.2, a_3=0.2$",
            "$\\varepsilon_1=\\varepsilon_2=2$\n$a_1=1, a_2=0.2, a_3=0.2$",
            "$\\varepsilon_1=\\varepsilon_2=1$\n$a_1=1, a_2=0.2, a_3=0.2$",
            "$\\varepsilon_1=0.2, \\varepsilon_2=1$\n$a_1=1, a_2=0.2, a_3=0.2$",
            "$\\varepsilon_1=\\varepsilon_2=0.2$\n$a_1=1, a_2=0.2, a_3=0.2$",
        ]
        xypos = (0.5, 0.05)
        self.draw_superquadrics(items)
        self.text(
            text,
            xypos,
            horizontalalignment="center",
            verticalalignment="top",
            fontsize=15,
        )

        self.save_fig(fig_format="pdf")
        self.show(fig_format="pdf")


create_empty_data_csv("./superquadrics.csv", 18)
MyStyle = MyStyle()
MyStyle.my_figure()
